### ISSUE TITLE
Arbitrary border color color removes arbitrary border width

### ISSUE THREAD

**Issue by alexmandrikdev** [gehrisandro/tailwind-merge-php#11]
## Current behaviour
`twMerge(['border-[0.85px] border-[#634D51]'])` -> `'border-[#634D51]'`
## Expected behaviour
`twMerge(['border-[0.85px] border-[#634D51]'])` -> `'border-[0.85px] border-[#634D51]'`

**Comment by gehrisandro** [comment]
Fixed in https://github.com/gehrisandro/tailwind-merge-php/releases/tag/v1.1.1
