### ISSUE TITLE
Remove Illuminate\Support

### ISSUE THREAD

**Issue by tobimori** [gehrisandro/tailwind-merge-php#3]
The dependency is quite heavy because of the use of 'Illuminate\Support' - is there any way you could get rid of this in the non-Laravel package (this one?).

**Comment by gehrisandro** [comment]
Yes, I'm currently working on this one.

But it was the quickest way for me to implement in the beginning 🙃

**Comment by gehrisandro** [comment]
@tobimori Done. Going to make a new release soon.

**Comment by tobimori** [comment]
Hi, when can you make a new release?
