### ISSUE TITLE
Grow TailwindMerge with PunteroRed

### ISSUE THREAD

**Issue by PunteroRed** [gehrisandro/tailwind-merge-php#5]
Hi Sandro Gehri,

We saw your profile and believe both Tailwind Merge and PHP might be a good fit for PunteroRed (maybe in a single org).
PunteroRed is helping OS projects to expand by registering as an NTC and tokenizing the project.

If interested, pls contact me via Telegram @MistBrown.

Thanks!

**Comment by gehrisandro** [comment]
no thanks
